### ISSUE TITLE
変換時に変換前の文字も入力される(iOS)

### ISSUE THREAD

**Issue by anko9801** [traPtitech/codimd#3]
例えば「てすと」を「テスト」に変換したいとき「てすテスト」となる

**Comment by hijiki51** [comment]
ipadで確認しましたが再現できません。環境を教えてもらってもいいですか？

**Comment by FujishigeTemma** [comment]
多分カスタムキーボードの実装に依存してると思う。
@anko9801 デフォルトのキーボードで再現しますか？

**Comment by anko9801** [comment]
なるほど。カスタムキーボードShimejiを切ったところ正しく動作しました。お騒がせしてすみません。
